# Generated by Django 2.2.6 on 2019-10-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='publicada',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
