# Generated by Django 2.2.6 on 2020-03-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20191004_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='visitas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
