# Generated by Django 2.2.6 on 2021-11-14 17:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0004_producto_visitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.PositiveIntegerField(default=1)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('estado_act', models.PositiveIntegerField(default=1)),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto')),
                ('tienda', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'En progreso'), (2, 'Confirmado'), (3, 'Retirar'), (4, 'Recibido'), (5, 'Cancelado'), (6, 'Suspendido')], default=1)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('transaccion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transaccion.Transaccion')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
