# Generated by Django 2.2.6 on 2020-03-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='usuario',
            new_name='cliente',
        ),
    ]
