# Generated by Django 2.2.6 on 2020-03-02 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0003_transaccion_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Listo'), (2, 'Cofirmado'), (3, 'Despachado'), (4, 'Recibido'), (5, 'Cancelado'), (6, 'Suspendido')], default=1)),
                ('transaccion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transaccion.Transaccion')),
            ],
        ),
    ]
