# Generated by Django 2.2.6 on 2020-03-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0004_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Listo'), (2, 'Cofirmado'), (3, 'Enviado'), (4, 'Recibido'), (5, 'Cancelado'), (6, 'Suspendido')], default=1),
        ),
    ]
