# Generated by Django 2.2.6 on 2020-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0010_auto_20200308_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'En progreso'), (2, 'Confirmado'), (3, 'Retirar'), (4, 'Recibido'), (5, 'Cancelado'), (6, 'Suspendido')], default=1),
        ),
    ]
