# Generated by Django 2.2.6 on 2020-03-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0007_auto_20200302_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='estado_act',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
