# Generated by Django 2.2.6 on 2020-03-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20191004_2306'),
        ('reputacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor5', models.PositiveIntegerField(default=0)),
                ('valor4', models.PositiveIntegerField(default=0)),
                ('valor3', models.PositiveIntegerField(default=0)),
                ('valor2', models.PositiveIntegerField(default=0)),
                ('valor1', models.PositiveIntegerField(default=0)),
                ('votos', models.PositiveIntegerField(default=0)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Tienda')),
            ],
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
