# Generated by Django 2.2.6 on 2020-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputacion', '0002_auto_20200301_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputacion',
            name='valor5',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reputacion',
            name='votos',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
