# Generated by Django 2.2.6 on 2020-02-29 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0002_denuncia_denunciante'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
